version: '3.8'
services:
  gateway: 
    build: . # 会在指定目录寻找Dockerfile 构建镜像
    container_name: gateway
    ports:
      - "8000:8000"
    command: [/app/gateway]
    depends_on:
    # 应该来一些健康检查的 TODO
      - video
      - mysql-slave
    #stdin_open: true # 与 docker run -i  类似 打开容器的标准输出 与用户进行交互
    #tty: true    #分配一个伪终端 与-t类似    docker run -dit
    networks:
      - backend
    restart: on-failure:10
    environment:
    # 这个环境变量似乎不起作用
      - TZ=Asia/Shanghai

  video: 
    build: . 
    container_name: video
    command: [/app/video]
    depends_on:
      - mysql-master
      - mysql-slave
      - redis
    networks:
      - mysql
      - backend
    restart: on-failure:10
    environment:
      - TZ=Asia/Shanghai

  user: 
    build: .
    container_name: user
    command: [/app/user]
    depends_on:
      - mysql-master
      - mysql-slave
      - redis
    networks:
      - mysql
      - backend
    restart: on-failure:10
    environment:
    # 这个环境变量似乎不起作用
      - TZ=Asia/Shanghai

  relation: 
    build: .
    container_name: relation
    command: [/app/relation]
    depends_on:
      - mysql-master
      - mysql-slave
      - redis
      - dev-rabbitmq
    networks:
      - mysql
      - backend
    restart: on-failure:10
    environment:
    # 这个环境变量似乎不起作用
      - TZ=Asia/Shanghai

  message: 
    build: .
    container_name: message
    command: [/app/message]
    depends_on:
      - mysql-master
      - mysql-slave
    networks:
      - mysql
      - backend
    restart: on-failure:10
    environment:
    # 这个环境变量似乎不起作用
      - TZ=Asia/Shanghai

  favorite: 
    build: .
    container_name: favorite
    command: [/app/favorite]
    depends_on:
      - mysql-master
      - mysql-slave
      - redis
      - dev-rabbitmq
    networks:
      - mysql
      - backend
    restart: on-failure:10
    environment:
    # 这个环境变量似乎不起作用
      - TZ=Asia/Shanghai
  
  comment: 
    build: .
    container_name: comment
    command: [/app/comment]
    depends_on:
      - mysql-master
      - mysql-slave
      - redis
      - dev-rabbitmq
    networks:
      - mysql
      - backend
    restart: on-failure:10
    environment:
    # 这个环境变量似乎不起作用
      - TZ=Asia/Shanghai

  etcd:
    image: "quay.io/coreos/etcd:v3.5.5"
    container_name: etcd
    restart: on-failure
    privileged: true
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - "ALLOW_NONE_AUTHENTICATION=yes"
      - ETCD_API=3
      - ETCD_CERT_FILE="/path/to/server.crt"
      - ETCD_KEY_FILE="/path/to/server.key"
      - ETCD_AUTH="simple"
      - ETCD_AUTH_USER="douyin"
      - ETCD_AUTH_PASSWORD="douyin"
    networks:
      - backend

  mysql-master:
    container_name: mysql-master 
    image: mysql:latest
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin123456
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'douyin'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MASTER_SYNC_USER: syncuser
      MASTER_SYNC_PASSWORD: sync123456
      SYNC_ALLOW_HOST: '%'
      R_W_USER: rw_user
      R_W_USER_PASSWORD: rw123456
      R_W_USER_HOST: '%'
      R_W_DATABASE: '*'
      TZ: Asia/Shanghai
    volumes:
     # 可能需要注意的是 docker-entrypoint-initdb.d 再每次重启运行 都会启动一次
      - ./config/mysql/master.sh:/docker-entrypoint-initdb.d/master.sh #这个sh会在mysql启动后自动运行
      - ./config/mysql/douyin.sql:/docker-entrypoint-initdb.d/douyin.sql 
      - ./config/mysql/master.cnf:/etc/my.cnf
      - mysqlMasterData:/var/lib/mysql/
    networks:
      mysql:
        ipv4_address: 192.168.0.100

  mysql-slave:
    container_name: mysql-slave
    image: mysql:latest
    ports:
      - "13307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin123456
      MYSQL_DATABASE: 'douyin'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MASTER_HOST: 192.168.0.100
      MASTER_PORT: 3306
      MASTER_SYNC_USER: syncuser
      MASTER_SYNC_PASSWORD: sync123456
      R_USER: r_user
      R_USER_PASSWORD: r123456
      R_USER_HOST: '%'
      TZ: Asia/Shanghai
    volumes:
    # 这里sh和sql的执行顺序应该时按照字母序 先执行douyin.sql 再执行slave.sql
      - ./config/mysql/slave.sh:/docker-entrypoint-initdb.d/slave.sh
      - ./config/mysql/douyin.sql:/docker-entrypoint-initdb.d/douyin.sql 
      - ./config/mysql/slave.cnf:/etc/my.cnf
      - mysqlSlaveData:/var/lib/mysql/
    networks:
      mysql:
        ipv4_address: 192.168.0.101
    depends_on:
      - mysql-master
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - backend
    volumes:
      - redis:/data

  dev-rabbitmq:
    image: rabbitmq:3-management
    container_name: dev-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./config/rabbitmq/definitions.json:/opt/definitions.json:ro
      - ${PWD}/config/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - backend

networks:
  mysql:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
  backend: 

# volume 持久化数据
volumes:
  rabbitmq:
  # 有机会改一下名mysql_master
  mysqlMasterData:
  mysqlSlaveData:
  redis:


#    env_file:
#      - .env
# 可以用evn file 保存compose里的环境变量 明文