// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	VideoID     int64     `gorm:"column:video_id;not null" json:"video_id"`
	UserID      int64     `gorm:"column:user_id;not null" json:"user_id"`
	Content     string    `gorm:"column:content;not null" json:"content"`
	CreatedTime time.Time `gorm:"column:created_time;not null" json:"created_time"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
