// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessage = "message"

// Message mapped from table <message>
type Message struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Content    string    `gorm:"column:content;not null" json:"content"`
	CreateTime time.Time `gorm:"column:create_time;not null" json:"create_time"`
	FromUserID int64     `gorm:"column:from_user_id;not null" json:"from_user_id"`
	ToUserID   int64     `gorm:"column:to_user_id;not null" json:"to_user_id"`
	HasRead    int32     `gorm:"column:has_read;primaryKey" json:"has_read"`
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
