// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVideo = "video"

// Video mapped from table <video>
type Video struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AuthorID      int64     `gorm:"column:author_id;not null" json:"author_id"`
	PlayURL       string    `gorm:"column:play_url;not null;comment:存文件名 然后灵活更换CDN域名" json:"play_url"` // 存文件名 然后灵活更换CDN域名
	CoverURL      string    `gorm:"column:cover_url;not null" json:"cover_url"`
	Title         string    `gorm:"column:title;not null;comment:Title 增加全文索引 以便于搜索 ngram全文索引支持中文的插件 默认分词2" json:"title"` // Title 增加全文索引 以便于搜索 ngram全文索引支持中文的插件 默认分词2
	PublishTime   time.Time `gorm:"column:publish_time;not null" json:"publish_time"`
	FavoriteCount int64     `gorm:"column:favorite_count;not null" json:"favorite_count"`
	CommentCount  int64     `gorm:"column:comment_count;not null;comment:两个count是不是可以考虑删除 要的时候再去计算" json:"comment_count"` // 两个count是不是可以考虑删除 要的时候再去计算
	Topic         string    `gorm:"column:topic;not null;comment:视频的分类 前两个为固定字段 后面为tag隐式搜索" json:"topic"`                 // 视频的分类 前两个为固定字段 后面为tag隐式搜索
}

// TableName Video's table name
func (*Video) TableName() string {
	return TableNameVideo
}
