mode: "debug"  # debug 打印详细的日志 其他例如production 打印简略的日志
jwtSecret: "DYF的DikTok"

# 七牛云
bucket: 
accessKey: 
secretKey: 
ossDomain: 
myIP: "0.0.0.0:9998" # 用于用户临时访问视频和图片  设置为自己的主机IP+端口号

httpAddress:
  host: 0.0.0.0 #需要更换为主机的ip
  port: 7777 #更换为运行的端口
  videoAddress: "./douyinVideo"
  imageAddress: "./douyinImage"
  defaultCoverURL: "https://img.zcool.cn/community/0159355d7dad02a801211d53f6aa65.png@1280w_1l_2o_100sh.png"

mysqlMaster:
  host: 127.0.0.1 # docker：mysql-master:3306 本机：127.0.0.1:13306
  port: 13306
  username: root
  password: admin123456
  database: douyin
  maxOpenConn: 100
  maxIdleConn: 10

mysqlSlave:
  host: 127.0.0.1 # docker：mysql-slave:3306 本机：127.0.0.1:13307
  port: 13307
  username: root
  password: admin123456
  database: douyin
  maxOpenConn: 100
  maxIdleConn: 10

userRedis:
  host: 127.0.0.1 # docker：redis:6379 本机：127.0.0.1:6379
  port: 6379
  password:
  db: 0
  poolSize: 100

videoRedis:
  host: 127.0.0.1 # docker：redis:6379 本机：127.0.0.1:6379
  port: 6379
  password:
  db: 1
  poolSize: 100

commentRedis:
  host: 127.0.0.1 # docker：redis:6379 本机：127.0.0.1:6379
  port: 6379
  password:
  db: 2
  poolSize: 100

rabbitmq:
  host:  127.0.0.1 # docker： dev-rabbitmq:6379 本机：127.0.0.1:5672
  port: 5672
  user: user
  password: password