mode: "debug" # debug 打印详细的日志 其他例如production 打印简略的日志
jwtSecret: 
gptSecret: 
etcd_address:

# 七牛云
qiniu:
  bucket: 
  accessKey: 
  secretKey: 
  ossDomain: 

http:
  host: 0.0.0.0 #需要更换为主机的ip
  port: 8000 #更换为运行的端口
  videoAddress: "./diktokVideo"

mysqlMaster:
  host: mysql_master # docker：mysql-master:3306 本机：127.0.0.1:13306
  port: 3306
  username: root
  password: admin123456
  database: diktok
  maxOpenConn: 100
  maxIdleConn: 10

mysqlSlave:
  host: mysql_slave # docker：mysql-slave:3306 本机：127.0.0.1:13307
  port: 3306
  username: root
  password: admin123456
  database: diktok
  maxOpenConn: 100
  maxIdleConn: 10

redis:
  host: redis # docker：redis:6379 本机：127.0.0.1:6379
  port: 6379
  password:
  poolSize: 100
  user_db: 0
  video_db: 1
  relation_db: 2
  favorite_db: 3
  comment_db: 4

mongo:
  host: 
  port: 
  user: 
  password: 
  db: 

rabbitmq:
  host: dev_rabbitmq # docker： dev-rabbitmq:6379 本机：127.0.0.1:5672
  port: 5672
  user: user
  password: password

otel_collector:
  host: otel_collector
  port: 4318
