#!/bin/bash
set -e
# 文件需要有可执行权限
## create user for sync
MASTER_SYNC_USER=${MASTER_SYNC_USER:-sync_admin} #默认为 "sync_admin" 不然就从环境遍历读物
MASTER_SYNC_PASSWORD=${MASTER_SYNC_PASSWORD:-sync_admin123456}
ROOT_USER="root"
ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-admin123456}
SYNC_ALLOW_HOST=${SYNC_ALLOW_HOST:-%}
CREATE_SYNC_USER_SQL="CREATE USER '$MASTER_SYNC_USER'@'$SYNC_ALLOW_HOST' IDENTIFIED WITH mysql_native_password BY '$MASTER_SYNC_PASSWORD';"
GRANT_SYNC_PRIVILEGES_SQL="GRANT REPLICATION SLAVE,REPLICATION CLIENT ON *.* TO '$MASTER_SYNC_USER'@'$SYNC_ALLOW_HOST';"
FLUSH_SYNC_PRIVILEGES_SQL="FLUSH PRIVILEGES;"
mysql -u"$ROOT_USER" -p"$ROOT_PASSWORD" -e "$CREATE_SYNC_USER_SQL" #-e 执行上面的sql语句
mysql -u"$ROOT_USER" -p"$ROOT_PASSWORD" -e "$GRANT_SYNC_PRIVILEGES_SQL"
mysql -u"$ROOT_USER" -p"$ROOT_PASSWORD" -e "$FLUSH_SYNC_PRIVILEGES_SQL"
## 如下用户是为了给程序添加可读可写的账号，不是用于主从同步的。
R_W_USER=${R_W_USER:-u_rw}
R_W_USER_PASSWORD=${R_W_USER_PASSWORD:-urw_pwd123456}
R_W_USER_HOST=${R_W_USER_HOST:-%}
R_W_DATABASE=${R_W_DATABASE:-*}
CREATE_R_W_USER_SQL="CREATE USER '$R_W_USER'@'$R_W_USER_HOST' IDENTIFIED WITH mysql_native_password BY '$R_W_USER_PASSWORD';"
GRANT_R_W_PRIVILEGES_SQL="GRANT XA_RECOVER_ADMIN,CREATE,DROP,INSERT,UPDATE,DELETE,SELECT ON $R_W_DATABASE.* TO '$R_W_USER'@'$R_W_USER_HOST';"
FLUSH_R_W_PRIVILEGES_SQL="FLUSH PRIVILEGES;"
mysql -u"$ROOT_USER" -p"$ROOT_PASSWORD" -e "$CREATE_R_W_USER_SQL"
mysql -u"$ROOT_USER" -p"$ROOT_PASSWORD" -e "$GRANT_R_W_PRIVILEGES_SQL"
mysql -u"$ROOT_USER" -p"$ROOT_PASSWORD" -e "$FLUSH_R_W_PRIVILEGES_SQL"